# server
server:
  port: 9998

# spring
spring:
  datasource:
    # h2 database
    driver-class-name: org.h2.Driver # h2 database 連接位址
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # 配置driver
    username: sa
    password:

    #    # oracle database
    #    driver-class-name: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@localhost:1521/ORCL # 配置driver
    #    username: system
    #    password: 123456

    # mysql database
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/mysql_local?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    #    username: root
    #    password: 123456
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 60000

  jpa:
    show-sql: true
    # mysql
    #    database: mysql
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    # oracle
    #    database: oracle
    # database-platform: org.hibernate.dialect.OracleDialect
    # h2
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update
      format_sql: true

  h2:
    console:
      enabled: true

  thymeleaf:
    cache: false
    prefix: "classpath:/templates/app/"
    suffix: .html

  web:
    resources:
      static-locations:
        - classpath:/static/

  #  security:
  #    user:
  #      name: admin
  #      password: 123456

  jackson:
    default-property-inclusion: non-null # JSON處理時忽略非空字段
    serialization:
      fail-on-empty-beans: false

  # cache
  cache:
    type: redis

  # redis
  data:
    redis:
      database: 0       # Redis資料庫索引（預設為0）
      host: 127.0.0.1   # Redis伺服器地址
      port: 6379        # Redis伺服器連線埠
      password:         # Redis伺服器連線密碼（預設為空）
      timeout: 5000     # 連線超時時間（毫秒）
      jedis:
        pool:
          max-active: 8 # 連線池最大連線數（使用負值表示沒有限制）
          max-wait: -1  # 連線池最大等待時間（使用負值表示沒有限制）
          max-idle: 8   # 連線池中的最大空閒連線
          min-idle: 0   # 連線池中的最小空閒連線

# slf4j
logging:
  file:
    name: bpiRestFulApi.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework: INFO
    com.bpi: DEBUG

# myBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件
  type-aliases-package: com.bpi.model.entity  # 實體類所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #console印sql



